# Generated by Django 4.1.5 on 2023-06-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_follow_account_user_name_alter_account_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="user_name",
            field=models.CharField(db_index=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
