# Generated by Django 4.1.5 on 2023-06-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_account_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="profile_image",
            field=models.ImageField(null=True, upload_to="profiles"),
        ),
    ]
