# Generated by Django 4.1.5 on 2023-06-11 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_account_profile_image"),
        ("feed", "0003_alter_post_image_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="account.account",
            ),
        ),
    ]
